#!/bin/sh

echo "All lines:"
cat src/*.java | wc

echo "Excluding empty lines:"
cat src/*.java | grep -v -e '^$' | wc

echo "Excluding empty lines and comments"
cat src/*.java | grep -v -e '^$' | grep -v '^[[:space:]]*//' | grep -v '^[[:space:]]*/*[[:space:]]*\*' | wc

echo "Excluding empty lines, comments, and lines containing a single bracket"
cat src/*.java | grep -v -e '^$' | grep -v '^[[:space:]]*//' | grep -v '^[[:space:]]*/*[[:space:]]*\*' | grep -v '^[[:space:]]*[{}][[:space:]]*$' | wc
