name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "Docs/*"
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  build:
    name: Build JAR File
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.5.0
    - name: Setup JDK
      uses: actions/setup-java@v3.11.0
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Compile Java
      run: |
        javac -d bin -cp src $(find src -name '*.java')
    - name: Build JAR file
      run: |
        cd bin
        jar cfm JDec.jar manifest.txt *.class
      
    - name: Build JDec JAR file
      run: |
        cd bin
        jar cfm JDec.jar manifest.txt $(find . -name '*.class')
    - name: Upload JAR file
      uses: actions/upload-artifact@v3.1.2
      with:
        name: JDec-JAR
        path: bin/JDec.jar
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
        - name: Windows
          tag: windows-latest
          separator: '\;'
        - name: Ubuntu
          tag: ubuntu-latest
          separator: ':'
    name: Unit Tests (${{ matrix.os.name }})
    runs-on: ${{ matrix.os.tag }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v1
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin # Eclipse Temurin
        java-version: '11'    # Java 11 (LTS)
        cache: 'maven'
    - name: Run Tests
      run: |
        mvn test
    - name: Publish Test Results
      if: ${{ always() }}
      uses: mikepenz/action-junit-report@v3
      with:
        report_paths: "**/TEST-*.xml"
        check_name: Test Results - ${{ matrix.os.name }}

